[package]
name = "libipld"
version = "0.11.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "library for dealing with ipld"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
async-trait = "0.1.42"
cached = { version = "0.23.0", default-features = false }
fnv = "1.0.7"
libipld-cbor = { version = "0.11.0", path = "dag-cbor", optional = true }
libipld-cbor-derive = { version = "0.11.0", path = "dag-cbor-derive", optional = true }
libipld-core = { version = "0.11.0", path = "core" }
libipld-json = { version = "0.11.0", path = "dag-json", optional = true }
libipld-macro = { version = "0.11.0", path = "macro" }
libipld-pb = { version = "0.11.0", path = "dag-pb", optional = true }
log = "0.4.14"
multihash = { version = "0.13.2", default-features = false, features = ["multihash-impl"] }
parking_lot = "0.11.1"
thiserror = "1.0.23"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
criterion = "0.3.4"
proptest = "0.10.1"
model = "0.1.2"
multihash = "0.13.2"

[features]
default = ["dag-cbor", "dag-json", "dag-pb", "derive"]
dag-cbor = ["libipld-cbor"]
dag-json = ["libipld-json"]
dag-pb = ["libipld-pb"]
derive = ["libipld-cbor-derive"]
unleashed = ["libipld-core/unleashed", "libipld-cbor/unleashed", "libipld-json/unleashed"]

[workspace]
members = [
  "core",
  "dag-cbor",
  "dag-cbor-derive",
  "dag-json",
  "dag-pb",
  "macro",
]

[profile.release]
debug = true

[[bench]]
name = "codec"
harness = false

[[bench]]
name = "store"
harness = false
